# Database configuration
database:
    # Type: sqlite (default), mysql, or mariadb
    type: "sqlite"
    # If you are using sqlite, you can configure the filename here (default: database.db)
    filename: "database.db"
    # If you are using MySQL/MariaDB, provide connection info here
    host: "localhost"
    port: 3306
    database: "database"
    username: "username"
    password: "password"

# Blacklisted worlds, which worlds should be excluded from the teleport actions?
# Example layout
# blacklisted-worlds:
#  - world
#  - world_nether

# StayPut redirects a teleport when it detects it is going to a world's spawn.
# Within how many blocks does a teleport location need to be near spawn
# in order to trigger redirection?
# Increasing may improve detection but increase false positives. 1 is recommended.
spawn-detection-threshold: 1

# Want to debug and see why certain actions are (not) executed? Set this to true. Default: false
debug: false